### ISSUE TITLE
Rewrite to Typescript 

### ISSUE THREAD

**Issue by ali-master** [wp-headless/fetch#1]
Hi @andrewmclagan.

What do you think to migrate this project to Typescript at the beginning level and before adding new features if needed?
I can help you to migrate if you agree.

**Comment by andrewmclagan** [comment]
Hey, yes would love to. Always was going to be the plan.

**Comment by andrewmclagan** [comment]
PR's welcome

**Comment by ali-master** [comment]
Great news. I'll start as soon as possible.

**Comment by andrewmclagan** [comment]
May be slow to review, but let see how it goes!

**Comment by andrewmclagan** [comment]
Closing in favour of an incoming PR
